name: "Build (Windows)"

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:

    - name: '🧰 Checkout'
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: 'Setup MSYS2'
      uses: msys2/setup-msys2@v2
      with:
        msystem: "MINGW64"
        update: true
        install: >-
          git
          make
          python3
          python3-pip
          mingw-w64-x86_64-toolchain

    - name: 'Build'
      run: |
        pip3 install quom
        make amalgamate
        make CFLAGS=-lws2_32 examples

    - name: 'Test'
      run: |
        ./examples/http_client.exe
